### PR TITLE
Python / Jython 2.2 support

### PR DESCRIPTION
**Pull request by clach04**
I noticed recent commits for Py 2.4, any interest in 2.2 support? The changes are fairly minimal. The test suite does NOT run clean but it now runs (wouldn't even start previously).

Also includes a doc string bug fix.

### CODE REVIEW

**Comment by cjerdonek** [comment]
Thanks for the suggestion. Personally, I'd like to finish releasing v0.5.0 from the development branch before modifying master to work with more versions. Also, I'd prefer making changes to support Python 3 before making changes to support older versions. The reasons I went ahead with the Python 2.4 changes are that two people independently expressed interest in it, the changes were easy enough, and Python 2.4 is readily available.  What's the best way to install Python 2.2, and does nose work with it?

**Comment by clach04** [comment]
> What's the best way to install Python 2.2,

For Jython you can; apt-get under Debian or get the jar file from http://www.jython.org/ - I would recommend this approach (as I used Jython for these changes).

If you are on Windows you can get a standalone MovPy version from http://code.google.com/p/movable-python/downloads/list - I think it may work under Wine too (untested).

> and does nose work with it?

Sadly no (or at least I once tried it and never pursued it further), that's why I added the unittest calls to two of the test scripts. I actually don't have Nose installed in my Py 2.4/6 environment so I wanted c3b098f irrespective of the 2.2 changes :-)

When you get chance check out the changes, they are really low impact. Full 2.2 support may be more work.

**Comment by cjerdonek** [comment]
Thanks for the info.  I think it's important to have a way to run all unit tests with a single command.  Are you running them for each module individually (with your change)?  From what I remember, unittest has as at least some test discovery capabilities that you can tap into (at least for some Python versions).

**Comment by clach04** [comment]
> Are you running them for each module individually (with your change)

I was, I didn't try "-m unittest" (I'd been assuming it wouldn't work for 2.2), I'll have to try that out.

**Comment by cjerdonek** [comment]
I just wanted to let you know that the v0.5.0 code was recently [merged to master](https://github.com/defunkt/pystache/commit/a4d763d54d83d4cbc9c254c897165563b119f7e8).  Are the 2.2 changes still fairly minimal?

Getting all the tests running correctly even with Python 2.4 was non-trivial -- mainly because of the spec tests.  The latest releases of Python's YAML and JSON libraries don't support Python 2.4, so using Python 2.4 requires an older version of [simplejson](http://pypi.python.org/pypi/simplejson/) (specifically any version of simplejson before 2.1.0).

**Comment by clach04** [comment]
The code has changed quite a lot in v0.5.0 :-) I've re-forked and applied changes. The changes are still fairly minimal but there are now more of them. Situation is similar, tests are now runnable but there are some failures. I'm not that familar with GitHub so you may get a new pull request from me shortly.

**Comment by clach04** [comment]
See https://github.com/defunkt/pystache/pull/103

**Pull request closed without merging**
