### PR TITLE
Fix to issue #91: Changing delimiters should only affect the upcoming text.

### PR DESCRIPTION
**Pull request by lucasb-eyer**
Fixes issue #91

I created a test case for the case from the bugreport and the fix passes it. It also passes all other tests. 

How it works is essentially what I described in the issue:
1. After a match/replacement, only continue searching from the beginning of the replacement on.
2. Do the replacement on the exact match, not the first string part resembling the matched text.

The behaviour now is the same as the behaviour in http://mustache.github.com/#demo

Edit: Argh, I'm new to fork-pull on github ; didn't want this to open two issues. (Also added a link to the issue.)

### CODE REVIEW

**Comment by lucasb-eyer** [comment]
I'm sorry, this does not actually pass all the tests. I forgot to run test_view.py and there it introduces one one test failure. I'm working on it now.

In addition, one test in test_pystache.py fails, but this very test fails with the exact same error without my changes too, so this failure is not introduced by this pull request.

**Comment by lucasb-eyer** [comment]
There we go, fixed it and now it really passes all tests. (Except for that one failure which is also present without my patch.)

Unfortunately, this doesn't fix issue #84 as I initially hoped. This is a different story.

**Comment by cjerdonek** [comment]
Sorry if you had to do unnecessary work. :(  By the way, running `nosetests` from the project directory runs all unit test modules, so you shouldn't need to run them individually.  I believe this is mentioned in the README (in both master and development).

**Comment by cjerdonek** [comment]
The issue that this pull request references has been closed.

**Comment by lucasb-eyer** [comment]
Oh, that teaches me to first check for dev branches next time :) Thanks for the pointer to `nosetests`, I read it but my brain didn't register it.

**Pull request closed without merging**
