### PR TITLE
Mustache spec v1.1.2 compliance: pull request

### PR DESCRIPTION
**Pull request by rbp**
This adds dot-notation support to pystache, thus making it compliant with Mustache spec v1.1.2. All tests passing, including spec tests.

### CODE REVIEW

**Comment by cjerdonek** [comment]
A couple comments:

I would put the bulk of your test cases (edge cases, etc) in `test_context.py` since the changes are to `context.py`.  And I would put a couple higher-level tests to test the connecting code in `test_renderengine.py` rather than `test_simple.py` since the former is the current go-forward location for spec-like tests.

**Comment by rbp** [comment]
Makes sense. Done.

**Comment by cjerdonek** [comment]
I could be missing something, but it doesn't look like your patch handles this case correctly:

```
>>> import pystache
>>> class D(object):
...   e = 'foo'
... 
>>> d = D()
>>> d.e
'foo'
>>> class A(object):
...   b = d
...   def c(self):
...     return d
... 
>>> a = A()
>>> a.b.e
'foo'
>>> a.c().e
'foo'
>>> pystache.render('{{b.e}} {{c.e}}', a)
u'foo '
```

The [spec says](https://github.com/mustache/spec/blob/master/specs/interpolation.yml#L12)--

> 2) Walk the context stack from top to bottom, finding the first context
> that is a) a hash containing the name as a key OR b) an object responding
> to a method with the given name.
> ...
> 4) If the context is an object, the data is the value returned by the
> method with the given name.

In the case above, `a` is an object responding to a method with name `'c'`, so at that part of the process the data should be the return value `a.c()`.

**Comment by maraujop** [comment]
**+1** for merging this into master. 

It took me some time to realize current implementation of pystache didn't support dot notaion. This fixes my issues, thanks Rodrigo.

**Comment by rbp** [comment]
@cjerdonek I know what's causing this, I "turned off" auto-calling when processing the intermediate steps in the dot path. My current code only auto-calls the last element. I actually did it on purpose, because I thought it made more sense. But I agree it breaks the spec. I'll fix it soon (probably over the weekend). Thanks for catching this!

**Comment by cjerdonek** [comment]
Great, thanks @rbp.  And if you could include a test case to cover this case (perhaps a modification of what I included above), that would help, too.

**Comment by cjerdonek** [comment]
FYI, I started taking a look at this more closely.  I may do a bit of refactoring prior to adding support for dot notation.  For example, I moved a bit of the name resolution logic from renderengine.py to context.py in this commit: 59a0d80911b4632625007a0959c6637f29228c3f.  I'll use your code and test cases as reference.  I'm also thinking about making a distinction between the notions of a "context" and a "context stack" to simplify things bit.

Lastly, I got a few clarifications on name resolution in this [issue](https://github.com/mustache/spec/issues/46) of the Mustache spec, which may help.

**Comment by richardhills** [comment]
I'm very keen to see these features incorporated too - thanks Rodrigo!

**Comment by rbp** [comment]
@cjerdonek Well, I've fixed the situation above whereby an intermediate object would not be called, and modified the proper test to reflect it. I'll take a look at your recent changes and merge them in my branch.

About the issue you mentioned, I think that's a bit orthogonal to this pull request, right?

@maraujop, @richardhills you're very welcome :)

**Comment by rbp** [comment]
@cjerdonek Ok, I've caught up with your refactoring (so far) :)

**Comment by tomplayford** [comment]
Thanks Rodrigo. Works well for me.

**Comment by cjerdonek** [comment]
Thanks again for the patch, @rbp.  I did make a couple changes to your logic since it didn't handle the following situation, for example:

```
>>> import pystache
>>> template = '{{#c}}"{{a}}" : "{{a.b}}"{{/c}}'
>>> context = {'a': {'b': 'b found: ERROR'}, 'c': {'a': 'b not found'}}
>>> pystache.render(template, context)
u'"b not found" : "b found: ERROR"'
```

I submitted a [pull request](https://github.com/mustache/spec/pull/48) to the Mustache spec to add a test case like this to their list of test cases.

Also, re: the [Mustache spec issue](https://github.com/mustache/spec/issues/46) I mentioned above, it is relevant because, strictly speaking, v1.1.2 of the spec also specifies behavior if the method on an object has an "arity of one":

```
4) If the context is an object and the method with the given name has an
arity of 1, the method SHOULD be called with a String containing the
unprocessed contents of the sections; the data is the value returned.
```

But your proposed patch didn't implement that.  In the issue I filed, I asked for clarification on that language, because it's not clear to me right now what that language even means.  Since they haven't responded with an answer yet, we can wait until a later date to address that aspect of v1.1.2.

I'll make a Pystache issue for us to address that point as a separate task.  Hopefully they will respond soon with clarification.

**Comment by cjerdonek** [comment]
Per my previous comment, I just created issue #116 to implement the "arity of one" language from v1.1.2.

**Pull request merged**
