### PR TITLE
Support python 2.4

### PR DESCRIPTION
**Pull request by wangtzINT**
I did some modification, now it works for python 2.4.

### CODE REVIEW

**Comment by jvantuyl** [comment]
Bump.  I could really use this.

**Comment by jvantuyl** [comment]
Actually, this patch is a bit messy.  I'll submit a cleaner pull request.

**Comment by wangtzINT** [comment]
Agree that this commit was a bit messy.

**Comment by wangtzINT** [comment]
BTW, I do think that modifications on template.py and nested_context.py are important, as python do not accept backward conditional expressions until python 2.5 

ref:http://docs.python.org/release/2.5/whatsnew/pep-308.html

> > > def f():
> > > ...     return 1 if 1 else 2
> > >   File "<stdin>", line 2
> > >     return 1 if 1 else 2

**Comment by cjerdonek** [comment]
I'll try to push this to PyPI in the next week or so.

**Comment by cjerdonek** [comment]
FYI, this has now been pushed to PyPI. Thanks for reporting.

**Pull request closed without merging**
